# permissions for end users to view kappcontrollerconfigs.
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRole
metadata:
  name: kappcontrollerconfig-viewer-role
rules:
- apiGroups:
  - run.tanzu.vmware.com
  resources:
  - kappcontrollerconfigs
  verbs:
  - get
  - list
  - watch
- apiGroups:
  - run.tanzu.vmware.com
  resources:
  - kappcontrollerconfigs/status
  verbs:
  - get
