apiVersion: vendir.k14s.io/v1alpha1
kind: Config
minimumRequiredVersion: 0.12.0
directories:
  - path: config/upstream
    contents:
      - path: addons-manager.yaml
        manual: {}
  - path: config/overlays
    contents:
      - path: overlay-addons-manager.yaml
        manual: {}
