name: Release

on:
  push:
    branches:
      - "!not_activated_on_branches!*"
    tags:
      - "v*"

jobs:

  build:
    name: Release
    runs-on: ubuntu-latest
    steps:

    - name: Set up Go 1.x
      uses: actions/setup-go@v2
      with:
        go-version: '1.16'
      id: go

    - name: Check out code into the Go module directory
      uses: actions/checkout@v1

    - name: Config credentials
      env:
        GH_ACCESS_TOKEN: ${{ secrets.GH_ACCESS_TOKEN }}
      run: |
        git config --global url."https://git:$GH_ACCESS_TOKEN@github.com".insteadOf "https://github.com"

    - name: Get dependencies
      run: |
        go get -v -t -d ./...
        if [ -f Gopkg.toml ]; then
            curl https://raw.githubusercontent.com/golang/dep/master/install.sh | sh
            dep ensure
        fi

    - name: Cache node modules
      uses: actions/cache@v2
      env:
        cache-name: cache-node-modules
      with:
        # npm cache files are stored in `~/.npm` on Linux/macOS
        path: ~/.npm
        key: ${{ runner.os }}-build-${{ env.cache-name }}-${{ hashFiles('**/package-lock.json') }}
        restore-keys: |
          ${{ runner.os }}-build-${{ env.cache-name }}-
          ${{ runner.os }}-build-
          ${{ runner.os }}-
    - name: Cache go modules with test results
      uses: actions/cache@v2
      with:
        path: |
          ~/.cache/go-build
          ~/go/pkg/mod
        key: ${{ runner.os }}-go-with-test-${{ hashFiles('**/go.sum') }}
        restore-keys: |
          ${{ runner.os }}-go-with-test-

    - name: Build
      run: make all

    - name: Test
      run: make test

    - id: upload-cli-artifacts
      uses: google-github-actions/upload-cloud-storage@main
      with:
        path: ./artifacts
        destination: tanzu-cli
        credentials: ${{ secrets.GCP_BUCKET_SA }}

    - id: upload-cli-admin-artifacts
      uses: google-github-actions/upload-cloud-storage@main
      with:
        path: ./artifacts-admin
        destination: tanzu-cli-admin-plugins
        credentials: ${{ secrets.GCP_BUCKET_SA }}

    - id: create_draft_release
      name: Create Draft Release
      uses: softprops/action-gh-release@v1
      with:
        draft: true
      env:
        GITHUB_TOKEN: ${{ secrets.GH_ACCESS_TOKEN }}